### PR TITLE
Make project single app

### PR DESCRIPTION
**Pull request by deni**
What do you think about this?

Followed [this one](https://zindilis.com/blog/2017/01/06/django-anatomy-for-single-app.html), but hadn't had a chance to test.

### CODE REVIEW

**Review by 2martens — APPROVED** [review]
Tested it and it works.

**Comment by deni** [comment]
What do you think? This way or the old one?

**Comment by 2martens** [comment]
I find the single app approach makes more sense naming wise.

**Comment by deni** [comment]
Then we agree. I have merged the PR.

**Pull request merged**
